uploadAddr: D:/SDNet-backend/upload
histPosition: D:/SDNet-backend/src/pycodes/splitAndPlotHist.py
environmentPosition: D:/Anaconda3/python.exe
encryptedImagePosition: D:/SDNet-backend/src/pycodes/randomImageDisplay.py
detectionPosition: D:/SDNet-backend/src/pycodes/Main_java.py
videoDetectionPosition: D:/SDNet-backend/src/pycodes/videoDetection.py


database:
  url: jdbc:mysql://localhost:3306/sdnet?useUnicode=true&characterEncoding=utf-8
  username: root
  password: '0911'
spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  application:
    name: SDBackend
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB
  profiles:
    active: pro

server:
  port: 8080

spring.mvc.static-path-pattern: /images/**
spring.resources.static-locations: file:D:/SDNet-backend/upload
